# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Homer Multitext project on github
tagline:          'Archival data and software for working with editions of Homeric manuscripts'
description:      ''
baseurl: 'http://homermultitext.github.io/'



author:
  name:           'Neel Smith'
 
paginate:         5

links:
  - title: HMT home page
    url: http://www.homermultitext.org/
    external: true
  - title: HMT editors' group
    url: http://hmteditors.github.io/
    external: true
  - title: HMT blog
    url: http://homermultitext.blogspot.com/
    external: true
  - title: Summer seminar
    url: /summerseminar2015/
  - title: Github source for this site
    url: https://github.com/homermultitext/homermultitext.github.io
    external: true

   