# Dependencies
markdown:         redcarpet
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Homer Multitext project on github
tagline:          'Archival data and software for working with editions of Homeric manuscripts'
description:      ''
baseurl: ''



author:
  name:           'Neel Smith'
 
paginate:         5

links:
  - title: About
    url: /about
  - title: Documentation
    url: http://homermultitext.github.io/hmt-docs
    external: true
  - title: Code
    url: /code
  - title: Data
    url: http://homermultitext.github.io/hmt-docs
    external: true
  - title: Links
    url: /links
