# Dependencies
markdown:         redcarpet
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Homer Multitext project on github
tagline:          'Archival data and software for working with editions of Homeric manuscripts'
description:      ''
baseurl: '/'



author:
  name:           'Neel Smith'
 
paginate:         5

links:
  - title: HMT home page
    url: http://www.homermultitext.org/
    external: true
  - title: HMT documentation
    url: /hmt-docs
  - title: HMT editors' group
    url: http://hmteditors.github.io/
    external: true
  - title: HMT blog
    url: http://homermultitext.blogspot.com/
    external: true
  - title: Github source for this site
    url: https://github.com/homermultitext/homermultitext.github.io
    external: true

   